"""Initial migration

Revision ID: a77217f699d1
Revises: 
Create Date: 2026-01-12 17:42:01.684302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a77217f699d1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nm_id', sa.Integer(), nullable=False),
    sa.Column('wb_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('wb_discount', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('spp', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('customer_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rrc', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_snapshots_nm_id'), 'price_snapshots', ['nm_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nm_id', sa.Integer(), nullable=False),
    sa.Column('vendor_code', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_nm_id'), 'products', ['nm_id'], unique=True)
    op.create_index(op.f('ix_products_vendor_code'), 'products', ['vendor_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_vendor_code'), table_name='products')
    op.drop_index(op.f('ix_products_nm_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_price_snapshots_nm_id'), table_name='price_snapshots')
    op.drop_table('price_snapshots')
    # ### end Alembic commands ###
