"""Capture a read-only baseline snapshot for SEO Phase 0 Step 1.

The script reads the current category-812 state and writes:

* matcher_v2 result snapshots for a handful of reference SKUs;
* deterministic query / SKU guard snapshots for reference examples;
* eval summary computed from the latest persisted matcher runs;
* manifest metadata tying everything to the current git SHA.

The script intentionally avoids mutating matcher / eval state in the database.
Run it from the API environment where Postgres is reachable, for example:

    python -m scripts.phase0.capture_baseline --project 1 --category 812 \
      --out tests/seo/phase0/baselines/812_pre_phase0
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from decimal import Decimal
from functools import lru_cache
from pathlib import Path
from typing import TYPE_CHECKING, Any, Mapping, Sequence


ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

if TYPE_CHECKING:
    from sqlalchemy.orm import Session


DEFAULT_REFERENCE_SKUS: tuple[int, ...] = (
    291861306,
    535441190,
)
DEFAULT_REFERENCE_SKU_COUNT = 5
DEFAULT_REFERENCE_QUERY_COUNT = 10


README_TEXT = """# Phase 0 baseline snapshots

These files capture the observable SEO baseline before Phase 0 backend
unification starts.

- Treat every file under `812_pre_phase0/` as read-only.
- Regenerate only via `python -m scripts.phase0.capture_baseline ...`.
- If a later step changes one of these snapshots, the diff must be explained
  and intentionally accepted.
"""


def _output_readme(command: str, git_sha: str) -> str:
    return (
        "# 812 pre-Phase-0 baseline\n\n"
        "This directory was generated by `scripts.phase0.capture_baseline`.\n\n"
        f"- command: `{command}`\n"
        f"- baseline_git_sha: `{git_sha}`\n"
        "- manifest source of truth: `manifest.json`\n"
        "- eval snapshot source of truth: `eval_summary.json`\n"
    )


@dataclass(frozen=True)
class ReferenceQuery:
    query_id: int
    normalized_query_text: str
    ranking_value_used: float | None


def _json_default(value: Any) -> Any:
    if isinstance(value, Decimal):
        return float(value)
    if isinstance(value, datetime):
        return value.isoformat()
    if isinstance(value, Path):
        return str(value)
    raise TypeError(f"Object of type {type(value)!r} is not JSON serializable")


def _write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True, default=_json_default)
        + "\n",
        encoding="utf-8",
    )


def _git_sha() -> str:
    from_env = os.getenv("BASELINE_GIT_SHA", "").strip()
    if from_env:
        return from_env
    try:
        completed = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=ROOT,
            check=True,
            capture_output=True,
            text=True,
        )
    except Exception:
        return "unknown"
    return completed.stdout.strip() or "unknown"


@lru_cache(maxsize=1)
def _runtime_imports() -> dict[str, Any]:
    from sqlalchemy import desc, func, select

    from app.db import SessionLocal
    from app.models import (
        SeoEvalLabel,
        SeoMatcherResult,
        SeoMatcherRun,
        SeoQueryAnnotation,
        SeoQueryClusterMembership,
        SeoSkuMeaningAnnotation,
    )
    from app.services.seo.atoms.v1.guards import apply_query_guards, apply_sku_guards
    from app.services.seo.atoms.v1.schemas import QueryAtoms, SkuAtoms
    from app.services.seo.eval.harness import (
        EVAL_THRESHOLDS,
        _collect_matcher_runs,
        _compute_metrics,
        _load_labels,
        _verdict_from_metrics,
    )

    return {
        "SessionLocal": SessionLocal,
        "desc": desc,
        "func": func,
        "select": select,
        "SeoEvalLabel": SeoEvalLabel,
        "SeoMatcherResult": SeoMatcherResult,
        "SeoMatcherRun": SeoMatcherRun,
        "SeoQueryAnnotation": SeoQueryAnnotation,
        "SeoQueryClusterMembership": SeoQueryClusterMembership,
        "SeoSkuMeaningAnnotation": SeoSkuMeaningAnnotation,
        "apply_query_guards": apply_query_guards,
        "apply_sku_guards": apply_sku_guards,
        "QueryAtoms": QueryAtoms,
        "SkuAtoms": SkuAtoms,
        "EVAL_THRESHOLDS": EVAL_THRESHOLDS,
        "_collect_matcher_runs": _collect_matcher_runs,
        "_compute_metrics": _compute_metrics,
        "_load_labels": _load_labels,
        "_verdict_from_metrics": _verdict_from_metrics,
    }


def _merge_reference_skus(
    seeded: Sequence[int],
    discovered: Sequence[int],
    *,
    limit: int,
) -> list[int]:
    merged: list[int] = []
    for nm_id in [*seeded, *discovered]:
        candidate = int(nm_id)
        if candidate in merged:
            continue
        merged.append(candidate)
        if len(merged) >= int(limit):
            break
    return merged


def _labeled_nm_ids(
    session: "Session",
    *,
    project_id: int,
    category_id: int,
    label_set_id: int,
) -> list[int]:
    runtime = _runtime_imports()
    select = runtime["select"]
    func = runtime["func"]
    SeoEvalLabel = runtime["SeoEvalLabel"]
    rows = session.execute(
        select(SeoEvalLabel.nm_id, func.count().label("label_count"))
        .where(
            SeoEvalLabel.project_id == int(project_id),
            SeoEvalLabel.category_id == int(category_id),
            SeoEvalLabel.label_set_id == int(label_set_id),
            SeoEvalLabel.nm_id.is_not(None),
        )
        .group_by(SeoEvalLabel.nm_id)
        .order_by(func.count().desc(), SeoEvalLabel.nm_id.asc())
    ).all()
    return [int(nm_id) for nm_id, _ in rows if nm_id is not None]


def _latest_matcher_run(
    session: "Session",
    *,
    project_id: int,
    category_id: int,
    nm_id: int,
) -> SeoMatcherRun | None:
    runtime = _runtime_imports()
    select = runtime["select"]
    desc = runtime["desc"]
    SeoMatcherRun = runtime["SeoMatcherRun"]
    return session.scalars(
        select(SeoMatcherRun)
        .where(
            SeoMatcherRun.project_id == int(project_id),
            SeoMatcherRun.category_id == int(category_id),
            SeoMatcherRun.nm_id == int(nm_id),
        )
        .order_by(desc(SeoMatcherRun.started_at), desc(SeoMatcherRun.id))
    ).first()


def _serialize_matcher_result(row: SeoMatcherResult) -> dict[str, Any]:
    return {
        "id": int(row.id),
        "query_meaning_id": int(row.query_meaning_id) if row.query_meaning_id is not None else None,
        "cluster_key": row.cluster_key,
        "query_display": str(row.query_display or ""),
        "normalized_query_text": str(row.normalized_query_text or ""),
        "bucket": str(row.bucket or ""),
        "eligibility_verdict": str(row.eligibility_verdict or ""),
        "score": float(row.score or 0),
        "score_components": dict(row.score_components or {}),
        "matched_atoms": list(row.matched_atoms or []),
        "missing_atoms": list(row.missing_atoms or []),
        "conflict_atoms": list(row.conflict_atoms or []),
        "reasons": list(row.reasons or []),
        "ranking_value_used": float(row.ranking_value_used) if row.ranking_value_used is not None else None,
        "semantic_similarity": float(row.semantic_similarity) if row.semantic_similarity is not None else None,
        "created_at": row.created_at.isoformat() if row.created_at else None,
    }


def _serialize_matcher_run(session: Session, run: SeoMatcherRun) -> dict[str, Any]:
    runtime = _runtime_imports()
    select = runtime["select"]
    SeoMatcherResult = runtime["SeoMatcherResult"]
    rows = session.scalars(
        select(SeoMatcherResult)
        .where(SeoMatcherResult.run_id == int(run.id))
        .order_by(SeoMatcherResult.score.desc(), SeoMatcherResult.id.asc())
    ).all()
    return {
        "run_id": int(run.id),
        "project_id": int(run.project_id),
        "category_id": int(run.category_id),
        "nm_id": int(run.nm_id),
        "matcher_version": str(run.matcher_version or ""),
        "policy_version": str(run.policy_version or ""),
        "category_profile_version": str(run.category_profile_version or ""),
        "sku_atoms_id": int(run.sku_atoms_id) if run.sku_atoms_id is not None else None,
        "vision_atoms_id": int(run.vision_atoms_id) if run.vision_atoms_id is not None else None,
        "query_atoms_version": run.query_atoms_version,
        "embedding_model": run.embedding_model,
        "quality_mode": str(run.quality_mode) if run.quality_mode else None,
        "degraded_reasons": list(run.degraded_reasons or []),
        "readiness_snapshot": dict(run.readiness_snapshot or {}),
        "metrics": dict(run.metrics or {}),
        "error": dict(run.error or {}) if run.error else None,
        "started_at": run.started_at.isoformat() if run.started_at else None,
        "completed_at": run.completed_at.isoformat() if run.completed_at else None,
        "results": [_serialize_matcher_result(row) for row in rows],
    }


def _select_reference_queries(
    session: "Session",
    *,
    project_id: int,
    category_id: int,
    limit: int,
) -> list[ReferenceQuery]:
    runtime = _runtime_imports()
    select = runtime["select"]
    SeoQueryAnnotation = runtime["SeoQueryAnnotation"]
    SeoQueryClusterMembership = runtime["SeoQueryClusterMembership"]
    rows = session.execute(
        select(
            SeoQueryAnnotation.id,
            SeoQueryAnnotation.normalized_query_text,
            SeoQueryClusterMembership.ranking_value_used,
        )
        .join(
            SeoQueryClusterMembership,
            SeoQueryClusterMembership.annotation_id == SeoQueryAnnotation.id,
        )
        .where(
            SeoQueryAnnotation.project_id == int(project_id),
            SeoQueryAnnotation.category_id == int(category_id),
        )
        .order_by(
            SeoQueryClusterMembership.ranking_value_used.desc(),
            SeoQueryAnnotation.id.asc(),
        )
        .limit(int(limit))
    ).all()
    return [
        ReferenceQuery(
            query_id=int(query_id),
            normalized_query_text=str(query_text or ""),
            ranking_value_used=float(ranking_value) if ranking_value is not None else None,
        )
        for query_id, query_text, ranking_value in rows
    ]


def _capture_query_snapshot(ref: ReferenceQuery) -> dict[str, Any]:
    runtime = _runtime_imports()
    apply_query_guards = runtime["apply_query_guards"]
    QueryAtoms = runtime["QueryAtoms"]
    atoms = apply_query_guards(QueryAtoms(), [ref.normalized_query_text])
    return {
        "query_id": ref.query_id,
        "normalized_query_text": ref.normalized_query_text,
        "ranking_value_used": ref.ranking_value_used,
        "atoms": atoms.model_dump(mode="json"),
    }


def _latest_sku_annotation(
    session: "Session",
    *,
    project_id: int,
    category_id: int,
    nm_id: int,
) -> SeoSkuMeaningAnnotation | None:
    runtime = _runtime_imports()
    select = runtime["select"]
    desc = runtime["desc"]
    SeoSkuMeaningAnnotation = runtime["SeoSkuMeaningAnnotation"]
    return session.scalars(
        select(SeoSkuMeaningAnnotation)
        .where(
            SeoSkuMeaningAnnotation.project_id == int(project_id),
            SeoSkuMeaningAnnotation.category_id == int(category_id),
            SeoSkuMeaningAnnotation.nm_id == int(nm_id),
        )
        .order_by(desc(SeoSkuMeaningAnnotation.updated_at), desc(SeoSkuMeaningAnnotation.id))
    ).first()


def _capture_sku_snapshot(
    session: "Session",
    *,
    project_id: int,
    category_id: int,
    nm_id: int,
) -> dict[str, Any]:
    runtime = _runtime_imports()
    apply_sku_guards = runtime["apply_sku_guards"]
    SkuAtoms = runtime["SkuAtoms"]
    annotation = _latest_sku_annotation(
        session,
        project_id=project_id,
        category_id=category_id,
        nm_id=nm_id,
    )
    if annotation is None:
        raise RuntimeError(
            f"No SeoSkuMeaningAnnotation found for project_id={project_id}, "
            f"category_id={category_id}, nm_id={nm_id}"
        )

    meaning_payload = dict(annotation.meaning_payload or {})
    source_metadata = dict(annotation.source_metadata or {})
    evidence_payload: dict[str, Any] = {
        "project_id": int(project_id),
        "category_id": int(category_id),
        "nm_id": int(nm_id),
        **source_metadata,
    }
    functional = meaning_payload.get("functional")
    product = evidence_payload.get("product")
    product_type = ""
    if isinstance(functional, Mapping):
        product_type = str(functional.get("product_type") or "")
    if not product_type and isinstance(product, Mapping):
        product_type = str(product.get("subject_name") or "")
    product_identity = ""
    if isinstance(product, Mapping):
        product_identity = str(product.get("title") or product.get("name") or "")

    atoms = apply_sku_guards(
        SkuAtoms(
            project_id=int(project_id),
            category_id=int(category_id),
            nm_id=int(nm_id),
            product_type=product_type,
            product_identity=product_identity,
            evidence_refs=["baseline_capture"],
        ),
        evidence=evidence_payload,
        meaning_payload=meaning_payload,
    )
    return {
        "nm_id": int(nm_id),
        "annotation_id": int(annotation.id),
        "schema_version": str(annotation.schema_version or ""),
        "status": str(annotation.status or ""),
        "meaning_payload": meaning_payload,
        "source_metadata": source_metadata,
        "atoms": atoms.model_dump(mode="json"),
    }


def _compute_eval_summary(
    session: "Session",
    *,
    project_id: int,
    category_id: int,
    label_set_id: int,
    nm_ids: Sequence[int],
) -> dict[str, Any]:
    runtime = _runtime_imports()
    select = runtime["select"]
    SeoMatcherResult = runtime["SeoMatcherResult"]
    EVAL_THRESHOLDS = runtime["EVAL_THRESHOLDS"]
    _collect_matcher_runs = runtime["_collect_matcher_runs"]
    _load_labels = runtime["_load_labels"]
    _compute_metrics = runtime["_compute_metrics"]
    _verdict_from_metrics = runtime["_verdict_from_metrics"]
    runs = _collect_matcher_runs(
        session,
        project_id=project_id,
        category_id=category_id,
        nm_ids=list(nm_ids),
        matcher_run_ids=None,
    )
    results_by_nm: dict[int, list[SeoMatcherResult]] = {}
    matcher_run_ids: list[int] = []
    resolved_nm_ids: list[int] = []
    for run in runs:
        matcher_run_ids.append(int(run.id))
        if int(run.nm_id) not in resolved_nm_ids:
            resolved_nm_ids.append(int(run.nm_id))
        rows = session.scalars(
            select(SeoMatcherResult).where(SeoMatcherResult.run_id == int(run.id))
        ).all()
        results_by_nm.setdefault(int(run.nm_id), []).extend(rows)

    labels = _load_labels(
        session,
        project_id=project_id,
        category_id=category_id,
        label_set_id=label_set_id,
        nm_ids=list(resolved_nm_ids) if resolved_nm_ids else None,
    )
    metrics, labels_used, labels_missing = _compute_metrics(
        labels=labels,
        results_by_nm=results_by_nm,
    )
    verdict = _verdict_from_metrics(metrics) if labels_used > 0 else "preview_only"
    return {
        "project_id": int(project_id),
        "category_id": int(category_id),
        "label_set_id": int(label_set_id),
        "verdict": str(verdict),
        "thresholds": dict(EVAL_THRESHOLDS),
        "metrics": dict(metrics),
        "matcher_run_ids": matcher_run_ids,
        "nm_ids": resolved_nm_ids,
        "labels_used": int(labels_used),
        "labels_missing": int(labels_missing),
    }


def _build_manifest(
    *,
    project_id: int,
    category_id: int,
    reference_sku_nm_ids: Sequence[int],
    reference_query_ids: Sequence[int],
    eval_summary: Mapping[str, Any],
) -> dict[str, Any]:
    metrics = eval_summary.get("metrics")
    accuracy = 0.0
    if isinstance(metrics, Mapping):
        accuracy = float(metrics.get("accuracy", 0.0) or 0.0)
    return {
        "baseline_git_sha": _git_sha(),
        "captured_at": datetime.now(timezone.utc).isoformat(),
        "project_id": int(project_id),
        "category_id": int(category_id),
        "reference_sku_nm_ids": [int(item) for item in reference_sku_nm_ids],
        "reference_query_ids": [int(item) for item in reference_query_ids],
        "eval_accuracy": round(accuracy, 4),
        "matcher_runs_referenced": [int(item) for item in eval_summary.get("matcher_run_ids", [])],
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Capture Phase 0 baseline artifacts.")
    parser.add_argument("--project", type=int, required=True, dest="project_id")
    parser.add_argument("--category", type=int, required=True, dest="category_id")
    parser.add_argument("--label-set-id", type=int, default=1)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--reference-sku-count", type=int, default=DEFAULT_REFERENCE_SKU_COUNT)
    parser.add_argument("--reference-query-count", type=int, default=DEFAULT_REFERENCE_QUERY_COUNT)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    out_dir = args.out.resolve()
    baselines_dir = out_dir.parent
    SessionLocal = _runtime_imports()["SessionLocal"]

    session = SessionLocal()
    try:
        discovered_nm_ids = _labeled_nm_ids(
            session,
            project_id=int(args.project_id),
            category_id=int(args.category_id),
            label_set_id=int(args.label_set_id),
        )
        reference_skus = _merge_reference_skus(
            DEFAULT_REFERENCE_SKUS,
            discovered_nm_ids,
            limit=int(args.reference_sku_count),
        )
        if not reference_skus:
            raise RuntimeError("No labeled SKU references found for baseline capture")

        reference_queries = _select_reference_queries(
            session,
            project_id=int(args.project_id),
            category_id=int(args.category_id),
            limit=int(args.reference_query_count),
        )
        if not reference_queries:
            raise RuntimeError("No query annotations found for baseline capture")

        for nm_id in reference_skus:
            run = _latest_matcher_run(
                session,
                project_id=int(args.project_id),
                category_id=int(args.category_id),
                nm_id=int(nm_id),
            )
            if run is None:
                raise RuntimeError(
                    f"No SeoMatcherRun found for project_id={args.project_id}, "
                    f"category_id={args.category_id}, nm_id={nm_id}"
                )
            _write_json(
                out_dir / f"matcher_v2_sku_{nm_id}.json",
                _serialize_matcher_run(session, run),
            )
            _write_json(
                out_dir / f"sku_atoms_{nm_id}.json",
                _capture_sku_snapshot(
                    session,
                    project_id=int(args.project_id),
                    category_id=int(args.category_id),
                    nm_id=int(nm_id),
                ),
            )

        for ref in reference_queries:
            _write_json(
                out_dir / f"query_atoms_{ref.query_id}.json",
                _capture_query_snapshot(ref),
            )

        eval_summary = _compute_eval_summary(
            session,
            project_id=int(args.project_id),
            category_id=int(args.category_id),
            label_set_id=int(args.label_set_id),
            nm_ids=discovered_nm_ids,
        )
        _write_json(out_dir / "eval_summary.json", eval_summary)
        _write_json(
            out_dir / "manifest.json",
            _build_manifest(
                project_id=int(args.project_id),
                category_id=int(args.category_id),
                reference_sku_nm_ids=reference_skus,
                reference_query_ids=[item.query_id for item in reference_queries],
                eval_summary=eval_summary,
            ),
        )
        (out_dir / "README.md").write_text(
            _output_readme(
                "python -m scripts.phase0.capture_baseline " + " ".join(sys.argv[1:]),
                _git_sha(),
            ),
            encoding="utf-8",
        )

        baselines_dir.mkdir(parents=True, exist_ok=True)
        readme_path = baselines_dir / "README.md"
        if not readme_path.exists():
            readme_path.write_text(README_TEXT, encoding="utf-8")
        init_path = baselines_dir / "__init__.py"
        if not init_path.exists():
            init_path.write_text('"""Phase 0 baseline snapshots."""\n', encoding="utf-8")
    finally:
        session.close()

    print(f"[ok] wrote baseline snapshot to {out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
